name: io_baxter_authentication
services:
  db:
    image: mysql:8.1
    container_name: authentication-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - ${MYSQL_PORTS}
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 3s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    container_name: authentication-redis
    restart: unless-stopped
    ports:
      - "4000:6379"

  api:
    build: .
    container_name: authentication-api
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      SPRING_R2DBC_URL: ${MYSQL_URL}
      SPRING_R2DBC_USERNAME: ${MYSQL_USER}
      SPRING_R2DBC_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      SPRING_REDIS_HOST: authentication-redis
      SPRING_REDIS_PORT: 6379
    ports:
      - ${API_PORTS}
    restart: unless-stopped

volumes:
  db_data:

networks:
  default:
    external: true
    name: baxter-net
